sudo: false
language: ruby
before_install: gem install bundler -v 1.10.6
rvm:
- 2.0.0
- 2.1.5
- 2.2.0
- 2.2.1
- 2.2.2
- 2.2.3
- rbx-2
- jruby-19mode
- ruby-head
- jruby-head
script:
- bundle exec rspec
addons:
  code_climate:
    repo_token:
      secure: D1HT1RpA+t8nZbXXD26rAyU8YJmaVFQXv+2yXmBmIca7d38zWz+SnJS8shtUXL48MRF31LC6ywTHjHi0JmCLKnwPQhddD8u8pecLGSOhc/wmdauDBTSlfYHo/2uErkVBix9oAgRvn/9b5sx7/yzq1PUWuhYgJhcnibECtQQQQkw=
notifications:
  hipchat:
    rooms:
      secure: HXE1RU8b95gp0/4QoQXws1dVSw+uHGg0wqb/q5EKBjvKXxaqfIrBWeZlTAn3ykz8HQja8YoUOlwFL7lpmwdbXlbmuSb0RPyqWURNvooDw3twn675E0dtf5vlKWbADsIK73Gs1LfR3Gpb0l/85T5P+/knNRkh9p43hqiRaW/LJ/M=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
matrix:
  allow_failures:
  - rvm: jruby-19mode
  - rvm: jruby-head
  - rvm: ruby-head
